services:
  - type: web
    name: phone-check-bot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python3 main.py"
    preBuildCommand: "apt-get update && apt-get install -y gcc"
    region: frankfurt
    plan: free
